from enum import Enum

class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class RunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    
class JobType(str, Enum):
    INGEST = "INGEST"
    VALIDATE_DATA = "VALIDATE_DATA"
    BUILD_FEATURES = "BUILD_FEATURES"
    GENERATE_PARENT_ORDERS = "GENERATE_PARENT_ORDERS"
    LABEL_IS = "LABEL_IS"
    BACKTEST_STRATEGIES = "BACKTEST_STRATEGIES"
    TCA_PIPELINE = "TCA_PIPELINE"
    RESEARCH_PIPELINE = "RESEARCH_PIPELINE"
    GENERATE_REPORTS = "GENERATE_REPORTS"
    FULL_RUN = "FULL_RUN"  # Virtual job that enqueues others
    
    # MNX Module (Alpha/Portfolio)
    MNX_INGEST_DAILY = "MNX_INGEST_DAILY"
    MNX_BUILD_FEATURES = "MNX_BUILD_FEATURES"
    MNX_TRAIN_RANKER = "MNX_TRAIN_RANKER"
    MNX_GENERATE_WEIGHTS = "MNX_GENERATE_WEIGHTS"
    MNX_GENERATE_BASKET = "MNX_GENERATE_BASKET"
    MNX_TO_NMIE_EXEC_SIM = "MNX_TO_NMIE_EXEC_SIM" # Bridge
    MNX_TUNE_MODEL = "MNX_TUNE_MODEL" # Hyperparameter Optimization
    
    # Orchestrator
    FULL_RUN_MNX_NMIE = "FULL_RUN_MNX_NMIE"
